# Generated by Django 5.2.7 on 2025-10-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('initial_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InitialWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_weights', to='investments.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_weights', to='investments.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='HoldingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('delta_units', models.DecimalField(decimal_places=10, max_digits=24)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_adjustments', to='investments.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_adjustments', to='investments.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'asset', 'effective_date'], name='investments_portfol_e153d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='investments.asset')),
            ],
            options={
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
