# Generated by Django 5.2.7 on 2025-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='initial_value',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
